BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Item" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "orderLine" (
	"numberOrder"	INTEGER NOT NULL,
	"idItem"	INTEGER NOT NULL,
	"numberOfElement"	INTEGER NOT NULL,
	PRIMARY KEY("numberOrder" AUTOINCREMENT),
	FOREIGN KEY("idItem") REFERENCES "Item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Ingredient" (
	"id"	INTEGER NOT NULL,
	"element"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "ItemIngredient" (
	"idItem"	INTEGER NOT NULL,
	"idIngredient"	INTEGER NOT NULL,
	PRIMARY KEY("idItem" AUTOINCREMENT),
	FOREIGN KEY("idItem") REFERENCES "Item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY("idIngredient") REFERENCES "Ingredient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Warehouse" (
	"id"	INTEGER NOT NULL,
	"idIngredient"	INTEGER NOT NULL,
	"numberOfElement"	INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY("idIngredient") REFERENCES "Ingredient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Etablishment" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Address" (
	"id"	INTEGER NOT NULL,
	"idConsumer"	INTEGER NOT NULL,
	"idEtablishment"	INTEGER NOT NULL,
	"streetNumber"	INTEGER,
	"nameOfStreet"	TEXT NOT NULL,
	"postalCode"	TEXT NOT NULL,
	"city"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idConsumer") REFERENCES "Consumer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY("idEtablishment") REFERENCES "Etablishment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Consumer" (
	"id"	INTEGER NOT NULL,
	"idAddress"	INTEGER NOT NULL,
	"firstName"	TEXT NOT NULL,
	"lastName"	TEXT NOT NULL,
	"gender"	TEXT NOT NULL,
	"phoneNumber"	TEXT,
	"mail"	TEXT,
	"password"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idAddress") REFERENCES "Address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Order" (
	"number"	INTEGER NOT NULL,
	"idConsumer"	INTEGER NOT NULL,
	"price"	TEXT,
	"timeOfOrder"	INTEGER,
	"dateOfOrder"	INTEGER,
	"paymentMethod"	TEXT,
	"delivryMethod"	TEXT,
	PRIMARY KEY("number" AUTOINCREMENT),
	FOREIGN KEY("idConsumer") REFERENCES "Consumer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
COMMIT;
