BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Ingredient" (
	"id"	INTEGER NOT NULL,
	"element"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Consumer" (
	"id"	INTEGER NOT NULL,
	"idAddress"	INTEGER NOT NULL,
	"firstName"	TEXT NOT NULL,
	"lastName"	TEXT NOT NULL,
	"gender"	TEXT NOT NULL,
	"phoneNumber"	TEXT NOT NULL,
	"mail"	TEXT NOT NULL,
	"password"	TEXT NOT NULL,
	"status"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idAddress") REFERENCES "Address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Address" (
	"id"	INTEGER NOT NULL UNIQUE,
	"idConsumer"	INTEGER NOT NULL,
	"idStore"	INTEGER NOT NULL,
	"streetNumber"	INTEGER,
	"nameOfStreet"	TEXT NOT NULL,
	"postalCode"	TEXT NOT NULL,
	"city"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idStore") REFERENCES "Store"("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY("idConsumer") REFERENCES "Consumer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Order" (
	"number"	INTEGER NOT NULL,
	"idConsumer"	INTEGER NOT NULL,
	"price"	NUMERIC NOT NULL,
	"orderEvent"	TEXT NOT NULL,
	"paymentMethod"	TEXT NOT NULL,
	"delivryMethod"	TEXT NOT NULL,
	PRIMARY KEY("number" AUTOINCREMENT),
	FOREIGN KEY("idConsumer") REFERENCES "Consumer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "HelpMemory" (
	"id"	INTEGER NOT NULL UNIQUE,
	"idPizza"	INTEGER NOT NULL,
	"idIngredient"	INTEGER NOT NULL,
	"quantity"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idPizza") REFERENCES "Pizza"("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY("idIngredient") REFERENCES "Ingredient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "Warehouse" (
	"id"	INTEGER NOT NULL UNIQUE,
	"idStore"	INTEGER NOT NULL,
	"idIngredient"	INTEGER NOT NULL,
	"numberOfElement"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idIngredient") REFERENCES "Ingredient"("id"),
	FOREIGN KEY("idStore") REFERENCES "Store"("id")
);
CREATE TABLE IF NOT EXISTS "orderLine" (
	"id"	INTEGER NOT NULL,
	"numberOrder"	INTEGER NOT NULL,
	"idPizza"	INTEGER NOT NULL,
	"quantity"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("idPizza") REFERENCES "Pizza"("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY("numberOrder") REFERENCES "Pizza"("idHelpMemory")
);
CREATE TABLE IF NOT EXISTS "Store" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Pizza" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
